jobs:
- job: Job1
  steps:
    - script: echo "This is Job1"
      displayName: "Run Job1"

- job: Job2
  dependsOn: Job1
  steps:
    - script: |
        if [[ "$(dependencies.Job1.result)" == "Succeeded" ]]; then
          echo "Job1 succeeded, proceed with Job2."
        else
          echo "Job1 failed, aborting Job2."
          exit 1
        fi
      displayName: "Check Job1 status and run Job2"
