stages:
- stage: Stage1
  jobs:
    - job: Job1
      steps:
        - script: echo "Running Stage1 Job"
          displayName: "Stage1 - Job1"

- stage: Stage2
  dependsOn: Stage1
  condition: eq(dependencies.Stage1.result, 'Succeeded')
  jobs:
    - job: Job2
      steps:
        - script: echo "Running Stage2 because Stage1 succeeded"
          displayName: "Stage2 - Job2"
