stages:
- stage: Stage1
  jobs:
    - job: Job1
      steps:
        - script: echo "Running Stage1 Job"
          displayName: "Stage1 - Job1"

- stage: Stage2
  dependsOn: Stage1
  variables:
    STAGE1_STATUS: $[ dependencies.Stage1.result ]
  jobs:
    - job: Job2
      steps:
        - script: |
            if [ "$STAGE1_STATUS" = "Succeeded" ]; then
              echo "Stage1 succeeded. Proceeding with Stage2."
            else
              echo "Stage1 did not succeed. Aborting Stage2."
              exit 1
            fi
          displayName: "Stage2 - Check Stage1 status"
